name: 'Semver Conventional Commits'
description: 'Calculate the next release version based on conventional commits since latest tag'
author: Nicolas Giard
inputs:
  token:
    description: GitHub Token
    required: true
  branch:
    description: The branch to use when fetching list of commits to compare against
    required: false
    default: main
  major-list:
    description: Comma separated commit prefixes, used to bump Major version
    required: false
    default:
  minor-list:
    description: Comma separated commit prefixes, used to bump Minor version
    required: false
    default: 'feat', 'feature'
  patch-list:
    description: Comma separated commit prefixes, used to bump Patch version
    required: false
    default: 'fix', 'bugfix', 'perf', 'refactor', 'test', 'tests'
  patch-all:
    description: If set to true, will ignore patch-list and count any commit as a Patch
    required: false
    default: false
outputs:
  current:
    description: Current version number
  next:
    description: Next version number in format v0.0.0
  nextStrict:
    description: Next version number without the v prefix
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: fast-forward
  color: red
