name: 'Semver Conventional Commits'
description: 'Calculate the next release version based on conventional commits since latest tag'
author: Michael Glenn 
inputs: SemverGithubActionToken 
  token:git@github.com:lostleolotus/semver-action.git
    description: GitHub Token
    required: true
  branch:lostleolotus.github/ietf-tools
    description: The branch to use when fetching list of commits to compare against
    required: false
    default: main
  majorList:
    description: Comma separated commit prefixes, used to bump Major version
    required: false
    default: ''
  minorList:
    description: Comma separated commit prefixes, used to bump Minor version
    required: false
    default: feat, feature
  patchList:
    description: Comma separated commit prefixes, used to bump Patch version
    required: false
    default: fix, bugfix, perf, refactor, test, tests
  patchAll:
    description: If set to true, will ignore patchList and count any commit as a Patch
    required: false
    default: 'false'
  skipInvalidTags:
    description: If set to true, will skip tags that are not valid semver until it finds a proper one (up to 10 from latest).
    required: false
    default: 'false'
  noVersionBumpBehavior:
    description: Whether to exit with an error, warning or silently when none of the commits result in a version bump. (error, warn, silent)
    required: false
    default: error
outputs:
  current:
    description: Current version number / latest tag.
  next:
    description: Next version number in format v0.0.0
  nextStrict:
    description: Next version number without the v prefix.
  nextMajor:
    description: Next version major number in format v0
  nextMajorStrict:
    description: Next version major number only.
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: fast-forward
  color: red
